version: "3"

services:
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./temp:/app/temp
    depends_on:
      - cpp-runner
      - python-runner
      - java-runner

  cpp-runner:
    build:
      context: ./docker-images/cpp
    image: code-runner-cpp
    container_name: cpp-runner

  python-runner:
    build:
      context: ./docker-images/python
    image: code-runner-python
    container_name: python-runner

  java-runner:
    build:
      context: ./docker-images/java
    image: code-runner-java
    container_name: java-runner
